<?php 

  
  $myPDO = new PDO('mysql:host=localhost;dbname=travel', 'root', '');
        $sql="SELECT * FROM destinations";
        $query=$myPDO->prepare($sql);
        $query->execute(array());
        $names = [
		    'EiffelTower.jpg',
			'ArcdeTriomphe.jpg',
			'CathedraleNotreDame.jpg', 
			'BasiliquedeFourviere.jpg',
			'CathedraleSaintJean.jpg',
			'ChateaudelaTourette.jpg',
			'ParcMartinLutherKing.jpg',
			'JardindesTuileries.jpg',
			'JardinduLuxembourg.jpg',
			'ParcdelaTetedor.jpg',
			'ParcdesbergesduRhone.jpg',
			'lemassifdelaSainteBaume.jpg',
			'lamontagneSainteVictoire.jpg',
			'lemontOlympe.jpg',
			'laBrevenne.jpg',
			'leGaron.jpg',
			'laCoise.jpg',
			'AbbayeSaintVictor.jpg',
			'ChateaudIf.jpg',
			'ChateaudelaBuzine.jpg',
			'StMarksBasilica.jpg',
			'PiazzaSanMarco.jpg',
			'SantaMariaGloriosa.jpg',
			'Lido.jpg',
			'TheColosseum.jpg',
			'VaticanCity.jpg',
			'ThePantheon.jpg',
			'SantaMarinella.jpg',
			'Anzio.jpg',
			'Duomo.jpg',
			'Aquaneva.jpg',
			'ParcAventura.jpg',
			'PizzodellaCroce.jpg',
			'RifugioMurelli.jpg',
			'AlgardoCarvao.jpg',
			'ParqueEduardoVII.jpg',
			'LisbonZoo.jpg',
			'TheTowerofBelem.jpg', 
			'MonsantoForest.jpg',
			'CaveRockBar.jpg',
			'CameraObscuraTavira.jpg',
			'PraiadaIlhadeTavira.jpg',
			'PrudencioNavarroZoo.jpg',
			'taviranationalpark.jpg',
			'CapSaintVincent.jpg',
			'BelichePortugal.jpg' ,
			'TemploRomanoEvora.jpg',
			'ParisZoological.jpg',
			'ThoiryZooSafari.jpg',
			'PraiadosPescadores.jpg',
			'PraiadoPeneco.jpg',
			'RuinasFingidas.jpg',
			'BrandenburgGate.jpg',
			'SpandauerForst.jpg',
			'Rixdorferhohe.jpg',
			'LesCavesWeine.jpg',
			'StrandbadGrunau.jpg',
			'VictoryColumn.jpg',
			'Mariensaule.jpg',
			'EnglishGarden.jpg',
			'BatCave.jpg',
			'HellabrunnZoo.jpg',
			'PerlacherMuggl.jpg',
			'AubingerLohe.jpg',
			'PlantenunBlomen.jpg',
			'ParkFiction.jpg',
			'MeiendorferForest.jpg',
			'WilderWaldWilhelmsburg.jpg',
			'TierparkHagenbeck.jpg',
			'TropenAquariumHagenbeck.jpg',
			'MountainBarcelona.jpg',
			'Tibidabo.jpg',
			'BarcelonetaBeach.jpg',
			'PlatjadelForum.jpg',
			'CovesdelSalnitre.jpg',
			'CaveofSaintIgnatius.jpg',
			'Penalara.jpg',
			'MountAbantos.jpg',
			'LaMaliciosa.jpg',
			'MadridForest.jpg',
			'UrbanBeachMadrid.jpg',
			'SaunaBeach.jpg',
			'TorredelOro.jpg',
			'MonumentoaJuan.jpg',
			'AlamilloPark.jpg',
			'ParquedeMariaLuisa.jpg',
			'PrincipesPark.jpg',
			'Minnewaterpark.jpg',
			'BoudewijnSeapark.jpg',
			'JeffdeBruges.jpg',
			'LaceJewel.jpg',
			'BoudewijnSeapark.jpg',
			'Serpentarium.jpg',
			'ResidencePalace.jpg',
			'InfantryMemorial.jpg',
			'BrusselsPark.jpg',
			'BoisdelaCambre.jpg',
			'BrusselsZoo.jpg',
			'DesignMuseumGent.jpg',
			'Penyghent.jpg',
			'DulleGriet.jpg',
			'ParcMuink.jpg',
			'LondonTowerBridge.jpg',
			'StJamessPark.jpg',
			'MonsterMountains.jpg',
			'BetsomsHill.jpg',
			'HydePark.jpg',
			'QueenVictoriasStatue.jpg',
			'AlbertMemorial.jpg',
			'AinsdaleBeach.jpg',
			'PlattFieldsPark.jpg',
			'ClaytonVale.jpg',
			'MemorialedelTrasporto.jpg',
			'CrosbyBeach.jpg',
			'WallaseyBeach.jpg',
			'KnowsleySafari.jpg',
			'CroxtethPettingFarm.jpg'];
			
        $path = "img/destination/";
        //echo ($path.$names[0]);
        $i = 0;
        while($data = $query->fetch()){
        	echo $data["id"];
           	$sql1="UPDATE destinations SET img =? WHERE id=?";
           	$query1=$myPDO->prepare($sql1);
        	$query1->execute(array($path.$names[$i],$data["id"]));
        	$i++;
        }
        
 ?>