
package com.travel.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Fri Apr 09 01:30:12 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getDestName", namespace = "http://service.webservice.travel.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDestName", namespace = "http://service.webservice.travel.com/")

public class GetDestName {

    @XmlElement(name = "idDestType")
    private int idDestType;

    public int getIdDestType() {
        return this.idDestType;
    }

    public void setIdDestType(int newIdDestType)  {
        this.idDestType = newIdDestType;
    }

}

