
package com.travel.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Apr 15 16:37:44 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getDestResponse", namespace = "http://service.webservice.travel.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDestResponse", namespace = "http://service.webservice.travel.com/")

public class GetDestResponse {

    @XmlElement(name = "result")
    private com.travel.webservice.model.DestinationName result;

    public com.travel.webservice.model.DestinationName getResult() {
        return this.result;
    }

    public void setResult(com.travel.webservice.model.DestinationName newResult)  {
        this.result = newResult;
    }

}

